name: 'My Composite Action'
description: 'A composite action example'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
