name: CI
on: create

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: 8.1
        tools: composer:v2
    - name: Do stuff
      run: |
        php test.php ${{ github.ref_name }}
    - name: Set the value
      run: |
        echo "FOO=$(git status)" >> $GITHUB_ENV
    - name: Use the value
      run: |
        echo "cock and balls"
        # echo "${{ env.FOO }}"