name: Run this when a PR is closed

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed

jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Echo out
        run: |
          echo "This is our second PR"
          echo "PR ref = ${{ github.event.pull_request.head.ref }}"
          echo "General ref = ${{ github.ref }}"

  DoStuff:
    if: ${{ startsWith(github.event.pull_request.head.ref, 'feature/sc-') || startsWith(github.event.pull_request.head.ref, 'chore/sc-') || startsWith(github.event.pull_request.head.ref, 'bug/sc-') }}
    uses: ./.github/workflows/includeFromOthers.yml
    with:
      BRANCH: ${{ github.event.pull_request.head.ref }}
