name: Run this whenever you need to

on:
  workflow_dispatch

jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Check context"
        run: |
          echo "ref is ${{ github.ref }}"
          echo "ref_name is ${{ github.ref_name }}"

  DoStuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Included
        uses: ./.github/workflows/includeFromOthers.yml
        with:
          BRANCH: ${{ github.ref }}
