name: Run tests

on: [push, workflow_dispatch]

jobs:
  phptests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Env
        run: cp .env.ci .env
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
      - name: Composer
        run: composer install --no-interaction --optimize-autoloader --prefer-dist
      - name: Perform tests
        run: php vendor/bin/pest
